
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    #   - type: log
    #     paths: 
    #       - /data/devops/projects/ELK-Nginx/nginx/logs/access.log
    #     tags: ["k8s","data","filebeat","access"]
    #     multiline.pattern: '^\d{2}/[A-Za-z]{3}/\d{4}:\d{2}:\d{2}:\d{2} \+\d{4}'
    #     multiline.negate: true
    #     multiline.match: after
    # filebeat.config.modules.path: ${path.config}/modules.d/*.yml
    # output.logstash:
    #   hosts: ["192.168.1.67:5044"]
     - type: container
       paths:
         - /var/log/containers/*.log
       tags: ["k8s","data","filebeat","access"]
       processors:
         - add_kubernetes_metadata:
             host: 192.168.52.191
             matchers:
             - logs_path:
                 logs_path: "/var/log/containers/"
 
    processors:
      - add_host_metadata:

    output.logstash:
      hosts: ['192.168.52.191:5044']
